public enum ProtocolType
{
    // Release는 버튼을 눌렀다 떼는 동작
    CONTROLLER_UP_PRESS,
    CONTROLLER_UP_RELEASE,
    CONTROLLER_DOWN_PRESS,
    CONTROLLER_DOWN_RELEASE,
    CONTROLLER_LEFT_PRESS,
    CONTROLLER_LEFT_RELEASE,
    CONTROLLER_RIGHT_PRESS,
    CONTROLLER_RIGHT_RELEASE,
    CONTROLLER_FALL_PRESS,
    CONTROLLER_CONNECT,
    CONTROLLER_DISCONNECT
}